### PR TITLE
Close artifact file handles after writing them to the filesystem

### PR DESCRIPTION
**Pull request by eamansour**
For https://github.com/galasa-dev/projectmanagement/issues/1732

Changes:
- Changed the `FileSystem` interface to return a `WriteCloser` in the `Create` method instead of a `Writer`
- Added a call to close an artifact file after writing it to the filesystem

### CODE REVIEW

**Comment by galasa-team** [comment]
Build failed, see http://localhost:8001/api/v1/namespaces/tekton-pipelines/services/tekton-dashboard:http/proxy/#/namespaces/galasa-build/pipelineruns/repo-cli-pr-206-zcpcx for details. If you are unable to do so, please contact a member of the Galasa team.

**Review by techcobweb — APPROVED** [review]
Approved for merging once the release activity is done...

**Comment by galasa-team** [comment]
Build failed, see http://localhost:8001/api/v1/namespaces/tekton-pipelines/services/tekton-dashboard:http/proxy/#/namespaces/galasa-build/pipelineruns/repo-cli-pr-206-zcpcx-r-gklbs for details. If you are unable to do so, please contact a member of the Galasa team.

**Comment by galasa-team** [comment]
Build successful

**Comment by galasa-team** [comment]
Build successful

**Pull request merged**
