### PR TITLE
mcobbett 1377 overrides

### PR DESCRIPTION
**Pull request by techcobweb**
- [x] CLI overrides are passed to the JVM
- [x] `--overridefile` is read and overrides within are used.
- [x] Temporary file in temporary folder created and passed to the JVM
- [x] Ras folder is always local using a hard-coded override.

### CODE REVIEW

**Comment by galasa-team** [comment]
Build successful

**Comment by galasa-team** [comment]
Build successful

**Comment by galasa-team** [comment]
Build successful

**Comment by galasa-team** [comment]
Build successful

**Comment by galasa-team** [comment]
Build successful

**Review by jadecarino — APPROVED** [review]

**Pull request merged**
