### PR TITLE
getting test-galasactl-ecosystem.sh to work

### PR DESCRIPTION
**Pull request by Akyiaa**
Currently `properties set` does not work for the `secure` namespace. However it works with other namespaces, eg `framework` and `ecosystem test`

This pr has an updated goal of getting the `test-galasactl-ecosystem.sh` working.

### CODE REVIEW

**Comment by galasa-team** [comment]
Build failed, see http://localhost:8001/api/v1/namespaces/tekton-pipelines/services/tekton-dashboard:http/proxy/#/namespaces/galasa-build/pipelineruns/repo-cli-pr-200-ns2ck for details. If you are unable to do so, please contact a member of the Galasa team.

**Comment by galasa-team** [comment]
Build failed, see http://localhost:8001/api/v1/namespaces/tekton-pipelines/services/tekton-dashboard:http/proxy/#/namespaces/galasa-build/pipelineruns/repo-cli-pr-200-frmlt for details. If you are unable to do so, please contact a member of the Galasa team.

**Comment by galasa-team** [comment]
Build failed, see http://localhost:8001/api/v1/namespaces/tekton-pipelines/services/tekton-dashboard:http/proxy/#/namespaces/galasa-build/pipelineruns/repo-cli-pr-200-p7nbq for details. If you are unable to do so, please contact a member of the Galasa team.

**Comment by galasa-team** [comment]
Build failed, see http://localhost:8001/api/v1/namespaces/tekton-pipelines/services/tekton-dashboard:http/proxy/#/namespaces/galasa-build/pipelineruns/repo-cli-pr-200-lhdf9 for details. If you are unable to do so, please contact a member of the Galasa team.

**Comment by galasa-team** [comment]
Build failed, see http://localhost:8001/api/v1/namespaces/tekton-pipelines/services/tekton-dashboard:http/proxy/#/namespaces/galasa-build/pipelineruns/repo-cli-pr-200-lb2wl for details. If you are unable to do so, please contact a member of the Galasa team.

**Comment by galasa-team** [comment]
Build successful

**Comment by Akyiaa** [comment]
It was found that for files with a lot of text inside them, using  `cat $output_file | grep $pattern -q` led to errors, even if the correct pattern was found in the file.
The `-q` grep flag exits with a 0 status as soon as the first instance of `$pattern` is found. However since the text in the file is large, `cat` would still be reading the file and writing it to std output when `grep` has already exited. This causes an `rc` of 141.

Hence I updated the tests to use the grep syntax of `grep $pattern $output_file -q` in `runs-tests.sh`. Since the other tests scripts which use grep do not have huge amounts of text being saved to a file to be grepped, I did not change the method of grepping (`cat $output_file | grep $pattern -q`).

**Review by techcobweb — APPROVED** [review]

**Pull request merged**
