### PR TITLE
Add galasactl secrets set command

### PR DESCRIPTION
**Pull request by eamansour**
## Why?
See https://github.com/galasa-dev/projectmanagement/issues/1467

## Changes
- Added `galasactl secrets set` command to create and update secrets in a Galasa service
  - Includes `--username`, `--password`, and `--token` flags to provide unencoded credentials, and base64-equivalents to provide base64-encoded credentials (e.g. `--base64-username`, `--base64-password`, etc.)
  - Added `--type` flag to be able to change the type of an existing secret

**This PR builds upon changes in https://github.com/galasa-dev/cli/pull/301 and https://github.com/galasa-dev/cli/pull/300 - those PRs should be delivered first, then this PR can be rebased to remove the duplicate changes**

**Builds for this PR will fail until https://github.com/galasa-dev/framework/pull/662 is delivered**

### CODE REVIEW

**Comment by galasa-team** [comment]
Build failed, see http://localhost:8001/api/v1/namespaces/tekton-pipelines/services/tekton-dashboard:http/proxy/#/namespaces/galasa-build/pipelineruns/repo-cli-pr-302-jvq6q for details. If you are unable to do so, please contact a member of the Galasa team.

**Review by techcobweb — APPROVED** [review]

**Comment by galasa-team** [comment]
Build failed, see http://localhost:8001/api/v1/namespaces/tekton-pipelines/services/tekton-dashboard:http/proxy/#/namespaces/galasa-build/pipelineruns/repo-cli-pr-302-6xwbb for details. If you are unable to do so, please contact a member of the Galasa team.

**Comment by galasa-team** [comment]
Build failed, see http://localhost:8001/api/v1/namespaces/tekton-pipelines/services/tekton-dashboard:http/proxy/#/namespaces/galasa-build/pipelineruns/repo-cli-pr-302-8xd8q for details. If you are unable to do so, please contact a member of the Galasa team.

**Comment by galasa-team** [comment]
Build failed, see http://localhost:8001/api/v1/namespaces/tekton-pipelines/services/tekton-dashboard:http/proxy/#/namespaces/galasa-build/pipelineruns/repo-cli-pr-302-86brt for details. If you are unable to do so, please contact a member of the Galasa team.

**Comment by galasa-team** [comment]
Build failed, see http://localhost:8001/api/v1/namespaces/tekton-pipelines/services/tekton-dashboard:http/proxy/#/namespaces/galasa-build/pipelineruns/repo-cli-pr-302-drdvx for details. If you are unable to do so, please contact a member of the Galasa team.

**Comment by galasa-team** [comment]
Build successful

**Comment by galasa-team** [comment]
Build successful

**Pull request merged**
