### PR TITLE
edited ValidateStream function to not return in the middle for readability

### PR DESCRIPTION
**Pull request by Wyvinar**

### CODE REVIEW

**Comment by galasa-team** [comment]
Build failed, see http://localhost:8001/api/v1/namespaces/tekton-pipelines/services/tekton-dashboard:http/proxy/#/namespaces/galasa-build/pipelineruns/repo-cli-pr-142-fz62c for details. If you are unable to do so, please contact a member of the Galasa team.

**Comment by techcobweb** [comment]
Build failed: 
```
Launching test on an ecosystem... directly... without a portfolio.
➜ Command is: /workspace/git/repo-cli-pr-142-fz62c/cli/bin/galasactl-linux-amd64 runs submit     --bootstrap http://galasa-cicsk8s.hursley.ibm.com/bootstrap     --class dev.galasa.inttests/dev.galasa.inttests.core.local.CoreLocalJava11Ubuntu     --stream inttests
    --throttle 1     --poll 10     --progress 1     --log -
2023/08/31 12:50:16 Galasa CLI - Submit tests (Remote)
2023/08/31 12:50:16 Galasa home is '/root/.galasa'
2023/08/31 12:50:16 NewRemoteLauncher(http://galasa-cicsk8s.hursley.ibm.com/) entered.
2023/08/31 12:50:16 Using group name 'c06c0c82-833a-42ca-93f8-83878737d708' for test run submission
2023/08/31 12:50:16 GetRunsByGroup(c06c0c82-833a-42ca-93f8-83878737d708) entered.
2023/08/31 12:50:16 Getting streams list.
2023/08/31 12:50:16 Validating that stream inttests exists in the list of valid streams.
2023/08/31 12:50:16 Stream is found in the list of valid streams.
fatal error: panic while printing panic value: type runtime.errorString
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x5a2220]

goroutine 1 [running]:
runtime.throw({0xc0002ba100?, 0x88f409?})
	/usr/local/go/src/runtime/panic.go:1077 +0x5c fp=0xc00010b618 sp=0xc00010b5e8 pc=0x438e1c
runtime.preprintpanics.func1()
	/usr/local/go/src/runtime/panic.go:576 +0xbc fp=0xc00010b6b0 sp=0xc00010b618 pc=0x4626dc
runtime.deferCallSave(0xc00010b768, 0xcb6fa0?)
	/usr/local/go/src/runtime/panic.go:798 +0x84 fp=0xc00010b6c0 sp=0xc00010b6b0 pc=0x4385a4
runtime.runOpenDeferFrame(0xc0002c01e0)
	/usr/local/go/src/runtime/panic.go:771 +0x1b8 fp=0xc00010b700 sp=0xc00010b6c0 pc=0x4383d8
panic({0x8198c0?, 0xfc75b0?})
	/usr/local/go/src/runtime/panic.go:914 +0x21f fp=0xc00010b7b0 sp=0xc00010b700 pc=0x43885f
runtime.panicmem(...)
	/usr/local/go/src/runtime/panic.go:261
runtime.sigpanic()
	/usr/local/go/src/runtime/signal_unix.go:861 +0x378 fp=0xc00010b810 sp=0xc00010b7b0 pc=0x44efd8
[github.com/galasa.dev/cli/pkg/errors.(*GalasaError](http://github.com/galasa.dev/cli/pkg/errors.(*GalasaError)).Error(0xc0002ba0c0?)
	/workspace/git/repo-cli-pr-142-fz62c/cli/pkg/errors/errorMessage.go:64 fp=0xc00010b818 sp=0xc00010b810 pc=0x5a2220
runtime.preprintpanics(0xc0002c01e0?)
	/usr/local/go/src/runtime/panic.go:582 +0x74 fp=0xc00010b878 sp=0xc00010b818 pc=0x437c94
panic({0x8198c0?, 0xfc75b0?})
	/usr/local/go/src/runtime/panic.go:1015 +0x39e fp=0xc00010b928 sp=0xc00010b878 pc=0x4389de
runtime.panicmem(...)
	/usr/local/go/src/runtime/panic.go:261
runtime.sigpanic()
	/usr/local/go/src/runtime/signal_unix.go:861 +0x378 fp=0xc00010b988 sp=0xc00010b928 pc=0x44efd8
[github.com/galasa.dev/cli/pkg/errors.(*GalasaError](http://github.com/galasa.dev/cli/pkg/errors.(*GalasaError)).GetMessageType(...)
	/workspace/git/repo-cli-pr-142-fz62c/cli/pkg/errors/errorMessage.go:41
[github.com/galasa.dev/cli/pkg/cmd.extractErrorDetails](http://github.com/galasa.dev/cli/pkg/cmd.extractErrorDetails)({0x81d420?, 0x0?})
	/workspace/git/repo-cli-pr-142-fz62c/cli/pkg/cmd/root.go:89 +0x4b fp=0xc00010b9d0 sp=0xc00010b988 pc=0x7c1e6b
[github.com/galasa.dev/cli/pkg/cmd.finalWord](http://github.com/galasa.dev/cli/pkg/cmd.finalWord)({0x81d420?, 0x0?})
	/workspace/git/repo-cli-pr-142-fz62c/cli/pkg/cmd/root.go:55 +0x2f fp=0xc00010baa8 sp=0xc00010b9d0 pc=0x7c1b4f
[github.com/galasa.dev/cli/pkg/cmd.Execute.func1()](http://github.com/galasa.dev/cli/pkg/cmd.Execute.func1())
	/workspace/git/repo-cli-pr-142-fz62c/cli/pkg/cmd/root.go:46 +0x1d fp=0xc00010bac8 sp=0xc00010baa8 pc=0x7c4add
runtime.deferCallSave(0xc00010bb80, 0xcb67a8?)
	/usr/local/go/src/runtime/panic.go:798 +0x84 fp=0xc00010bad8 sp=0xc00010bac8 pc=0x4385a4
runtime.runOpenDeferFrame(0xc0002c0190)
	/usr/local/go/src/runtime/panic.go:771 +0x1b8 fp=0xc00010bb18 sp=0xc00010bad8 pc=0x4383d8
panic({0x81d420?, 0x0?})
	/usr/local/go/src/runtime/panic.go:914 +0x21f fp=0xc00010bbc8 sp=0xc00010bb18 pc=0x43885f
[github.com/galasa.dev/cli/pkg/cmd.executeSubmit](http://github.com/galasa.dev/cli/pkg/cmd.executeSubmit)(0xc000114800?, {0xc0001422a0?, 0x4?, 0x881180?})
	/workspace/git/repo-cli-pr-142-fz62c/cli/pkg/cmd/runsSubmit.go:141 +0x2d1 fp=0xc00010bd60 sp=0xc00010bbc8 pc=0x7c42d1
[github.com/spf13/cobra.(*Command](http://github.com/spf13/cobra.(*Command)).execute(0xfd2980, {0xc0001421c0, 0xe, 0xe})
	/go/pkg/mod/github.com/spf13/cobra@v1.1.3/command.go:856 +0x67b fp=0xc00010be48 sp=0xc00010bd60 pc=0x594b9b
[github.com/spf13/cobra.(*Command](http://github.com/spf13/cobra.(*Command)).ExecuteC(0xfd1800)
	/go/pkg/mod/github.com/spf13/cobra@v1.1.3/command.go:960 +0x389 fp=0xc00010bf00 sp=0xc00010be48 pc=0x595169
[github.com/spf13/cobra.(*Command](http://github.com/spf13/cobra.(*Command)).Execute(...)
	/go/pkg/mod/github.com/spf13/cobra@v1.1.3/command.go:897
[github.com/galasa.dev/cli/pkg/cmd.Execute()](http://github.com/galasa.dev/cli/pkg/cmd.Execute())
	/workspace/git/repo-cli-pr-142-fz62c/cli/pkg/cmd/root.go:50 +0x37 fp=0xc00010bf30 sp=0xc00010bf00 pc=0x7c1ad7
main.main()
	/workspace/git/repo-cli-pr-142-fz62c/cli/cmd/galasactl/main.go:13 +0xf fp=0xc00010bf40 sp=0xc00010bf30 pc=0x7c534f
runtime.main()
	/usr/local/go/src/runtime/proc.go:267 +0x2bb fp=0xc00010bfe0 sp=0xc00010bf40 pc=0x43b7fb
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:1650 +0x1 fp=0xc00010bfe8 sp=0xc00010bfe0 pc=0x46a9a1

goroutine 2 [force gc (idle)]:
runtime.gopark(0x0?, 0x0?, 0x0?, 0x0?, 0x0?)
	/usr/local/go/src/runtime/proc.go:398 +0xce fp=0xc000056fa8 sp=0xc000056f88 pc=0x43bc4e
runtime.goparkunlock(...)
	/usr/local/go/src/runtime/proc.go:404
runtime.forcegchelper()
	/usr/local/go/src/runtime/proc.go:322 +0xb3 fp=0xc000056fe0 sp=0xc000056fa8 pc=0x43bad3
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:1650 +0x1 fp=0xc000056fe8 sp=0xc000056fe0 pc=0x46a9a1
created by runtime.init.6 in goroutine 1
	/usr/local/go/src/runtime/proc.go:310 +0x1a

goroutine 3 [GC sweep wait]:
runtime.gopark(0x0?, 0x0?, 0x0?, 0x0?, 0x0?)
	/usr/local/go/src/runtime/proc.go:398 +0xce fp=0xc000057778 sp=0xc000057758 pc=0x43bc4e
runtime.goparkunlock(...)
	/usr/local/go/src/runtime/proc.go:404
runtime.bgsweep(0x0?)
	/usr/local/go/src/runtime/mgcsweep.go:280 +0x94 fp=0xc0000577c8 sp=0xc000057778 pc=0x427c54
runtime.gcenable.func1()
	/usr/local/go/src/runtime/mgc.go:200 +0x25 fp=0xc0000577e0 sp=0xc0000577c8 pc=0x41cd85
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:1650 +0x1 fp=0xc0000577e8 sp=0xc0000577e0 pc=0x46a9a1
created by runtime.gcenable in goroutine 1
	/usr/local/go/src/runtime/mgc.go:200 +0x66

goroutine 4 [GC scavenge wait]:
runtime.gopark(0xc000076000?, 0xd248d0?, 0x1?, 0x0?, 0xc000006d00?)
	/usr/local/go/src/runtime/proc.go:398 +0xce fp=0xc000057f70 sp=0xc000057f50 pc=0x43bc4e
runtime.goparkunlock(...)
	/usr/local/go/src/runtime/proc.go:404
runtime.(*scavengerState).park(0xfd8800)
	/usr/local/go/src/runtime/mgcscavenge.go:425 +0x49 fp=0xc000057fa0 sp=0xc000057f70 pc=0x425489
runtime.bgscavenge(0x0?)
	/usr/local/go/src/runtime/mgcscavenge.go:653 +0x3c fp=0xc000057fc8 sp=0xc000057fa0 pc=0x425a1c
runtime.gcenable.func2()
	/usr/local/go/src/runtime/mgc.go:201 +0x25 fp=0xc000057fe0 sp=0xc000057fc8 pc=0x41cd25
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:1650 +0x1 fp=0xc000057fe8 sp=0xc000057fe0 pc=0x46a9a1
created by runtime.gcenable in goroutine 1
	/usr/local/go/src/runtime/mgc.go:201 +0xa5

goroutine 17 [finalizer wait]:
runtime.gopark(0x400000?, 0x100056670?, 0x0?, 0x0?, 0x1008960?)
	/usr/local/go/src/runtime/proc.go:398 +0xce fp=0xc000056628 sp=0xc000056608 pc=0x43bc4e
runtime.runfinq()
	/usr/local/go/src/runtime/mfinal.go:193 +0x107 fp=0xc0000567e0 sp=0xc000056628 pc=0x41be07
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:1650 +0x1 fp=0xc0000567e8 sp=0xc0000567e0 pc=0x46a9a1
created by runtime.createfing in goroutine 1
	/usr/local/go/src/runtime/mfinal.go:163 +0x3d

goroutine 7 [IO wait]:
runtime.gopark(0x410225?, 0xb?, 0x0?, 0x0?, 0x6?)
	/usr/local/go/src/runtime/proc.go:398 +0xce fp=0xc0000a6ab8 sp=0xc0000a6a98 pc=0x43bc4e
runtime.netpollblock(0x4b7eb8?, 0x407de6?, 0x0?)
	/usr/local/go/src/runtime/netpoll.go:564 +0xf7 fp=0xc0000a6af0 sp=0xc0000a6ab8 pc=0x434777
internal/poll.runtime_pollWait(0x7f7086786e10, 0x72)
	/usr/local/go/src/runtime/netpoll.go:343 +0x85 fp=0xc0000a6b10 sp=0xc0000a6af0 pc=0x465745
internal/poll.(*pollDesc).wait(0xc0000f2900?, 0xc000212000?, 0x0)
	/usr/local/go/src/internal/poll/fd_poll_runtime.go:84 +0x27 fp=0xc0000a6b38 sp=0xc0000a6b10 pc=0x4d3587
internal/poll.(*pollDesc).waitRead(...)
	/usr/local/go/src/internal/poll/fd_poll_runtime.go:89
internal/poll.(*FD).Read(0xc0000f2900, {0xc000212000, 0x1000, 0x1000})
	/usr/local/go/src/internal/poll/fd_unix.go:164 +0x27a fp=0xc0000a6bd0 sp=0xc0000a6b38 pc=0x4d487a
net.(*netFD).Read(0xc0000f2900, {0xc000212000?, 0x6e1860?, 0xfd0700?})
	/usr/local/go/src/net/fd_posix.go:55 +0x25 fp=0xc0000a6c18 sp=0xc0000a6bd0 pc=0x528505
net.(*conn).Read(0xc00005a018, {0xc000212000?, 0x0?, 0xc0000061a0?})
	/usr/local/go/src/net/net.go:179 +0x45 fp=0xc0000a6c60 sp=0xc0000a6c18 pc=0x534f45
net.(*TCPConn).Read(0x4?, {0xc000212000?, 0x408d9a?, 0x21?})
	<autogenerated>:1 +0x25 fp=0xc0000a6c90 sp=0xc0000a6c60 pc=0x544465
net/http.(*persistConn).Read(0xc0000bad80, {0xc000212000?, 0xc00009c600?, 0xc0000a6d38?})
	/usr/local/go/src/net/http/transport.go:1954 +0x4a fp=0xc0000a6cf0 sp=0xc0000a6c90 pc=0x6e7b2a
bufio.(*Reader).fill(0xc00007a0c0)
	/usr/local/go/src/bufio/bufio.go:113 +0x103 fp=0xc0000a6d28 sp=0xc0000a6cf0 pc=0x546783
bufio.(*Reader).Peek(0xc00007a0c0, 0x1)
	/usr/local/go/src/bufio/bufio.go:151 +0x53 fp=0xc0000a6d48 sp=0xc0000a6d28 pc=0x5468b3
net/http.(*persistConn).readLoop(0xc0000bad80)
	/usr/local/go/src/net/http/transport.go:2118 +0x1b9 fp=0xc0000a6fc8 sp=0xc0000a6d48 pc=0x6e8919
net/http.(*Transport).dialConn.func5()
	/usr/local/go/src/net/http/transport.go:1776 +0x25 fp=0xc0000a6fe0 sp=0xc0000a6fc8 pc=0x6e7145
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:1650 +0x1 fp=0xc0000a6fe8 sp=0xc0000a6fe0 pc=0x46a9a1
created by net/http.(*Transport).dialConn in goroutine 18
	/usr/local/go/src/net/http/transport.go:1776 +0x169f

goroutine 8 [select]:
runtime.gopark(0xc0000a2f90?, 0x2?, 0xe0?, 0x2d?, 0xc0000a2f1c?)
	/usr/local/go/src/runtime/proc.go:398 +0xce fp=0xc0000a2db8 sp=0xc0000a2d98 pc=0x43bc4e
runtime.selectgo(0xc0000a2f90, 0xc0000a2f18, 0xc000034140?, 0x0, 0xc00019e8d0?, 0x1)
	/usr/local/go/src/runtime/select.go:327 +0x725 fp=0xc0000a2ed8 sp=0xc0000a2db8 pc=0x44b605
net/http.(*persistConn).writeLoop(0xc0000bad80)
	/usr/local/go/src/net/http/transport.go:2421 +0xe5 fp=0xc0000a2fc8 sp=0xc0000a2ed8 pc=0x6ea2e5
net/http.(*Transport).dialConn.func6()
	/usr/local/go/src/net/http/transport.go:1777 +0x25 fp=0xc0000a2fe0 sp=0xc0000a2fc8 pc=0x6e70e5
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:1650 +0x1 fp=0xc0000a2fe8 sp=0xc0000a2fe0 pc=0x46a9a1
created by net/http.(*Transport).dialConn in goroutine 18
	/usr/local/go/src/net/http/transport.go:1777 +0x16f1
✖ Failed to submit a test to a remote ecosystem.

Step failed
```

**Comment by techcobweb** [comment]
Perhaps you can run this locally ? test-galasactl-ecosystem.sh --bootstrap http://galasa-cicsk8s.hursley.ibm.com/bootstrap

**Comment by galasa-team** [comment]
Build successful

**Pull request merged**
