### PR TITLE
galasactl launches test3

### PR DESCRIPTION
**Pull request by techcobweb**
- separate file generator from createProject command
- rebasing
- gradle should put boot jar in the correct place.
- adding templates for more properties files
- refactor runs submit to extract report generators
- make code more unit testable
- build-locally.sh changes - starting to test build portfolio
- throttle file holds throttle which can be changed.
- separate local processing. JAVA_HOME checked.
- preparation for launching a JVM. --local command is hidden
- copyright fix
- empty commit to prompt a build
- comment out unit test which relies on boot.jar being there. Until automation calls gradle
- don't rely on gradle being there when we make things
- try building again
- correction to cli pipeline
- forcing a build
- forcing a build
- forcing a build

### CODE REVIEW

**Comment by galasa-team** [comment]
Build failed, see https://tekton.galasa.dev/#/namespaces/galasa-pipelines/pipelineruns/repo-cli-pr-51-96dz2 for details

**Comment by galasa-team** [comment]
Build failed, see https://tekton.galasa.dev/#/namespaces/galasa-pipelines/pipelineruns/repo-cli-pr-51-fhwb2 for details

**Comment by galasa-team** [comment]
Build successful

**Comment by galasa-team** [comment]
Build successful

**Comment by galasa-team** [comment]
Build successful

**Review by AaronJhaj — APPROVED** [review]

**Pull request merged**
