### PR TITLE
test script uses an ecosystem CPS store

### PR DESCRIPTION
**Pull request by techcobweb**
Signed-off-by: Mike Cobbett <77053+techcobweb@users.noreply.github.com>

# Why ?
Story: Local test run to be able to use remote CPS
[#1813](https://github.com/galasa-dev/projectmanagement/issues/1813)

Tasks in this PR:
- add tests to the CLI project to make sure the hybrid local-test-using-remote-cps works.

### CODE REVIEW

**Comment by galasa-team** [comment]
Build failed, see http://localhost:8001/api/v1/namespaces/tekton-pipelines/services/tekton-dashboard:http/proxy/#/namespaces/galasa-build/pipelineruns/repo-cli-pr-236-wffw4 for details. If you are unable to do so, please contact a member of the Galasa team.

**Review by KirbyKatcher — APPROVED** [review]

**Comment by galasa-team** [comment]
Build failed, see http://localhost:8001/api/v1/namespaces/tekton-pipelines/services/tekton-dashboard:http/proxy/#/namespaces/galasa-build/pipelineruns/repo-cli-pr-236-c6dx2 for details. If you are unable to do so, please contact a member of the Galasa team.

**Comment by galasa-team** [comment]
Build failed, see http://localhost:8001/api/v1/namespaces/tekton-pipelines/services/tekton-dashboard:http/proxy/#/namespaces/galasa-build/pipelineruns/repo-cli-pr-236-7mlzq for details. If you are unable to do so, please contact a member of the Galasa team.

**Comment by galasa-team** [comment]
Build failed, see http://localhost:8001/api/v1/namespaces/tekton-pipelines/services/tekton-dashboard:http/proxy/#/namespaces/galasa-build/pipelineruns/repo-cli-pr-236-vlrck for details. If you are unable to do so, please contact a member of the Galasa team.

**Comment by techcobweb** [comment]
Build fails with 
```
Running the test code locally
➜ GALASA_BOOTSTRAP is not set. As we are launching a local run. Currently ''
➜ GALASA_HOME is /workspace/git/repo-cli-pr-236-vlrck/cli/temp/remote-cps/home
➜ Command is /workspace/git/repo-cli-pr-236-vlrck/cli/bin/galasactl-linux-x86_64 runs submit local --obr mvn:dev.galasa.cps.rest.test/dev.galasa.cps.rest.test.obr/0.0.1-SNAPSHOT/obr         --class dev.galasa.cps.rest.test.http/dev.galasa.cps.rest.test.http.TestHttp         --bootstrap file:///workspace/git/repo-cli-pr-236-vlrck/cli/temp/remote-cps/home/bootstrap.properties         --log -
       
2024/05/09 12:03:04 Galasa CLI - Submit tests (Local)
2024/05/09 12:03:04 Galasa home is '/workspace/git/repo-cli-pr-236-vlrck/cli/temp/remote-cps/home'
2024/05/09 12:03:04 Creating file of type jar at /workspace/git/repo-cli-pr-236-vlrck/cli/temp/remote-cps/home/lib/0.34.0/galasa-boot-0.31.0.jar
2024/05/09 12:03:04 File /workspace/git/repo-cli-pr-236-vlrck/cli/temp/remote-cps/home/lib/0.34.0/galasa-boot-0.31.0.jar exists, no need to create it then.
2024/05/09 12:03:04 Creating file of type properties at /workspace/git/repo-cli-pr-236-vlrck/cli/temp/remote-cps/home/bootstrap.properties
2024/05/09 12:03:04 File /workspace/git/repo-cli-pr-236-vlrck/cli/temp/remote-cps/home/bootstrap.properties exists, no need to create it then.
2024/05/09 12:03:04 Creating file of type properties at /workspace/git/repo-cli-pr-236-vlrck/cli/temp/remote-cps/home/overrides.properties
2024/05/09 12:03:04 File /workspace/git/repo-cli-pr-236-vlrck/cli/temp/remote-cps/home/overrides.properties exists, no need to create it then.
2024/05/09 12:03:04 Creating file of type properties at /workspace/git/repo-cli-pr-236-vlrck/cli/temp/remote-cps/home/cps.properties
2024/05/09 12:03:04 File /workspace/git/repo-cli-pr-236-vlrck/cli/temp/remote-cps/home/cps.properties exists, no need to create it then.
2024/05/09 12:03:04 Creating file of type properties at /workspace/git/repo-cli-pr-236-vlrck/cli/temp/remote-cps/home/dss.properties
2024/05/09 12:03:04 File /workspace/git/repo-cli-pr-236-vlrck/cli/temp/remote-cps/home/dss.properties exists, no need to create it then.
2024/05/09 12:03:04 Creating file of type properties at /workspace/git/repo-cli-pr-236-vlrck/cli/temp/remote-cps/home/credentials.properties
2024/05/09 12:03:04 File /workspace/git/repo-cli-pr-236-vlrck/cli/temp/remote-cps/home/credentials.properties exists, no need to create it then.
2024/05/09 12:03:04 Creating file of type properties at /workspace/git/repo-cli-pr-236-vlrck/cli/temp/remote-cps/home/galasactl.properties
2024/05/09 12:03:04 File /workspace/git/repo-cli-pr-236-vlrck/cli/temp/remote-cps/home/galasactl.properties exists, no need to create it then.
2024/05/09 12:03:04 Using group name 'e67f1241-9abf-4266-a907-07dedf40a14c' for test run submission
2024/05/09 12:03:04 JvmLauncher: GetRunsByGroup(groupName=e67f1241-9abf-4266-a907-07dedf40a14c) entered. 
2024/05/09 12:03:04 JvmLauncher: GetRunsByGroup(groupName=e67f1241-9abf-4266-a907-07dedf40a14c) exiting. isComplete:true testRuns returned:0
2024/05/09 12:03:04     Selected test class 'dev.galasa.cps.rest.test.http/dev.galasa.cps.rest.test.http.TestHttp'
2024/05/09 12:03:04 buildListOfRunsToSubmit - portfolio &{v1alpha [galasa.dev/testPortfolio](http://galasa.dev/testPortfolio) {adhoc} [{dev.galasa.cps.rest.test.http dev.galasa.cps.rest.test.http.TestHttp   map[] }]}, runOverrides map[]
2024/05/09 12:03:04 Added test /dev.galasa.cps.rest.test.http/dev.galasa.cps.rest.test.http.TestHttp to the ready queue
2024/05/09 12:03:04 submitRun - dev.galasa.cps.rest.test.http/dev.galasa.cps.rest.test.http.TestHttp, CLI
2024/05/09 12:03:04 JvmLauncher: SubmitTestRun entered. group=e67f1241-9abf-4266-a907-07dedf40a14c className=dev.galasa.cps.rest.test.http/dev.galasa.cps.rest.test.http.TestHttp requestType=CLI requestor=root stream= isTraceEnabled=false
2024/05/09 12:03:04 Properties file /tmp/galasa-3900106415overrides.properties written containing this:
framework.request.type.LOCAL.prefix=L
framework.resultarchive.store=file:////workspace/git/repo-cli-pr-236-vlrck/cli/temp/remote-cps/home/ras
zos3270.terminal.output=json,png
2024/05/09 12:03:04 [framework.config.store](http://framework.config.store/) bootstrap property indicates a remote CPS will be used. So we need a valid JWT.
2024/05/09 12:03:04 Retrieving bearer token from file '/workspace/git/repo-cli-pr-236-vlrck/cli/temp/remote-cps/home/bearer-token.json'
2024/05/09 12:03:04 Retrieved bearer token from file '/workspace/git/repo-cli-pr-236-vlrck/cli/temp/remote-cps/home/bearer-token.json' OK
2024/05/09 12:03:04 Validating bearer token retrieved from file '/workspace/git/repo-cli-pr-236-vlrck/cli/temp/remote-cps/home/bearer-token.json'
2024/05/09 12:03:04 Validated bearer token retrieved from file '/workspace/git/repo-cli-pr-236-vlrck/cli/temp/remote-cps/home/bearer-token.json' OK
2024/05/09 12:03:04 Launching command '/opt/java/openjdk/bin/java' '[-jar /workspace/git/repo-cli-pr-236-vlrck/cli/temp/remote-cps/home/lib/0.34.0/galasa-boot-0.31.0.jar -Dfile.encoding=UTF-8 -DGALASA_HOME="/workspace/git/repo-cli-pr-236-vlrck/cli/temp/remote-cps/home" --localmaven file:////root/.m2/repository --remotemaven https://repo.maven.apache.org/maven2 --bootstrap file:////workspace/git/repo-cli-pr-236-vlrck/cli/temp/remote-cps/home/bootstrap.properties --overrides file:////tmp/galasa-3900106415overrides.properties --obr mvn:dev.galasa.cps.rest.test/dev.galasa.cps.rest.test.obr/0.0.1-SNAPSHOT/obr --obr mvn:dev.galasa/dev.galasa.uber.obr/0.34.0/obr --test dev.galasa.cps.rest.test.http/dev.galasa.cps.rest.test.http.TestHttp -DGALASA_JWT=***redacted***
2024/05/09 12:03:04 JVM test started. Spawning a go routine to wait for it to complete.
2024/05/09 12:03:04 Don't have enough information to find the structure.json in the RAS folder.
2024/05/09 12:03:04 waiting for the JVM to complete within a go routine.
2024/05/09 12:03:05 JVM output: 09/05/2024 12:03:05.014 INFO dev.galasa.boot.Launcher.getGalasaHome - Environment variable GALASA_HOME used to set value of home location.
2024/05/09 12:03:05 JVM output: 09/05/2024 12:03:05.016 INFO dev.galasa.boot.Launcher.getGalasaHome - Galasa home location is /workspace/git/repo-cli-pr-236-vlrck/cli/temp/remote-cps/home
2024/05/09 12:03:05 JVM output: 09/05/2024 12:03:05.026 DEBUG dev.galasa.boot.Launcher.processCommandLine - Supplied command line arguments: -Dfile.encoding=UTF-8 -DGALASA_HOME="/workspace/git/repo-cli-pr-236-vlrck/cli/temp/remote-cps/home" --localmaven file:////root/.m2/repository --remotemaven https://repo.maven.apache.org/maven2 --bootstrap file:////workspace/git/repo-cli-pr-236-vlrck/cli/temp/remote-cps/home/bootstrap.properties --overrides file:////tmp/galasa-3900106415overrides.properties --obr mvn:dev.galasa.cps.rest.test/dev.galasa.cps.rest.test.obr/0.0.1-SNAPSHOT/obr --obr mvn:dev.galasa/dev.galasa.uber.obr/0.34.0/obr --test dev.galasa.cps.rest.test.http/dev.galasa.cps.rest.test.http.TestHttp -DGALASA_JWT=***redacted***
2024/05/09 12:03:05 JVM output: 09/05/2024 12:03:05.046 DEBUG dev.galasa.boot.Launcher.launch - OBR Repository Files: [mvn:dev.galasa.cps.rest.test/dev.galasa.cps.rest.test.obr/0.0.1-SNAPSHOT/obr, mvn:dev.galasa/dev.galasa.uber.obr/0.34.0/obr]
2024/05/09 12:03:05 JVM output: 09/05/2024 12:03:05.046 DEBUG dev.galasa.boot.Launcher.launch - Launching Framework...
2024/05/09 12:03:05 JVM output: 
2024/05/09 12:03:05 JVM output: 09/05/2024 12:03:05.046 DEBUG dev.galasa.boot.Launcher.buildFramework - Launching Framework...
2024/05/09 12:03:05 JVM output: 09/05/2024 12:03:05.047 DEBUG dev.galasa.boot.felix.FelixFramework.buildFramework - Building Felix Framework...
2024/05/09 12:03:05 JVM output: 09/05/2024 12:03:05.182 DEBUG dev.galasa.boot.felix.FelixFramework.buildFramework - Initializing Felix Framework
2024/05/09 12:03:05 JVM output: 09/05/2024 12:03:05.279 DEBUG dev.galasa.boot.felix.FelixFramework.buildFramework - Starting Felix Framework
2024/05/09 12:03:05 JVM output: 
2024/05/09 12:03:05 JVM output: 09/05/2024 12:03:05.282 DEBUG dev.galasa.boot.felix.FelixFramework.buildFramework - Felix Framework started
2024/05/09 12:03:05 JVM output: 
2024/05/09 12:03:05 JVM output: 09/05/2024 12:03:05.283 DEBUG dev.galasa.boot.felix.FelixFramework.buildFramework - Installing required OSGi bundles
2024/05/09 12:03:05 JVM output: 
2024/05/09 12:03:05 Don't have enough information to find the structure.json in the RAS folder.
2024/05/09 12:03:06 JVM output: 09/05/2024 12:03:06.095 DEBUG d.g.f.m.r.i.GalasaMavenUrlHandlerService - Checking https://repo.maven.apache.org/maven2
2024/05/09 12:03:06 JVM output: 09/05/2024 12:03:06.152 DEBUG d.g.f.m.r.i.GalasaMavenUrlHandlerService - Attempting to download https://repo.maven.apache.org/maven2/dev/galasa/dev.galasa.uber.obr/0.34.0/dev.galasa.uber.obr-0.34.0.obr with connection timeout of 300000ms and read timeout of 300000ms
2024/05/09 12:03:06 JVM output: 09/05/2024 12:03:06.703 DEBUG d.g.f.m.r.i.GalasaMavenUrlHandlerService - Checking https://repo.maven.apache.org/maven2
2024/05/09 12:03:06 JVM output: 09/05/2024 12:03:06.703 DEBUG d.g.f.m.r.i.GalasaMavenUrlHandlerService - Attempting to download https://repo.maven.apache.org/maven2/dev/galasa/dev.galasa.uber.obr/0.34.0/dev.galasa.uber.obr-0.34.0.obr with connection timeout of 300000ms and read timeout of 300000ms
2024/05/09 12:03:06 JVM output: 09/05/2024 12:03:06.764 ERROR dev.galasa.boot.Launcher.launch - Unable to run test class
2024/05/09 12:03:06 JVM output: dev.galasa.boot.LauncherException: Unable to create and initialize Felix framework
2024/05/09 12:03:06 JVM output: at dev.galasa.boot.Launcher.buildFramework([Launcher.java:221](http://launcher.java:221/))
	at dev.galasa.boot.Launcher.launch([Launcher.java:160](http://launcher.java:160/))
2024/05/09 12:03:06 JVM output: at dev.galasa.boot.Launcher.main([Launcher.java:126](http://launcher.java:126/))
2024/05/09 12:03:06 JVM output: Caused by: dev.galasa.boot.LauncherException: Unable to load repository mvn:dev.galasa/dev.galasa.uber.obr/0.34.0/obr
	at dev.galasa.boot.felix.FelixFramework.loadBundleRepositories([FelixFramework.java:887](http://felixframework.java:887/))
	at dev.galasa.boot.felix.FelixFramework.buildFramework([FelixFramework.java:120](http://felixframework.java:120/))
2024/05/09 12:03:06 JVM output: at dev.galasa.boot.Launcher.buildFramework([Launcher.java:218](http://launcher.java:218/))
	... 2 more
2024/05/09 12:03:06 JVM output: Caused by: java.io.IOException: Unable to locate maven artifact mvn:dev.galasa/dev.galasa.uber.obr/0.34.0/obr
2024/05/09 12:03:06 JVM output: at dev.galasa.framework.maven.repository.internal.GalasaMavenUrlHandlerService.openConnection([GalasaMavenUrlHandlerService.java:78](http://galasamavenurlhandlerservice.java:78/))
2024/05/09 12:03:06 JVM output: 
2024/05/09 12:03:06 JVM output: at org.apache.felix.framework.URLHandlersStreamHandlerProxy.openConnection([URLHandlersStreamHandlerProxy.java:270](http://urlhandlersstreamhandlerproxy.java:270/))
2024/05/09 12:03:06 JVM output: at java.base/java.net.URL.openConnection([URL.java:1074](http://url.java:1074/))
	at org.apache.felix.bundlerepository.impl.FileUtil.openURL([FileUtil.java:199](http://fileutil.java:199/))
2024/05/09 12:03:06 JVM output: at org.apache.felix.bundlerepository.impl.DataModelHelperImpl.repository([DataModelHelperImpl.java:113](http://datamodelhelperimpl.java:113/))
	at [org.apache.felix.bundlerepository.impl.RepositoryAdminImpl$1.run](http://org.apache.felix.bundlerepository.impl.repositoryadminimpl$1.run/)([RepositoryAdminImpl.java:115](http://repositoryadminimpl.java:115/))
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at org.apache.felix.bundlerepository.impl.RepositoryAdminImpl.addRepository([RepositoryAdminImpl.java:111](http://repositoryadminimpl.java:111/))
	at org.apache.felix.bundlerepository.impl.RepositoryAdminImpl.addRepository([RepositoryAdminImpl.java:99](http://repositoryadminimpl.java:99/))
	at org.apache.felix.bundlerepository.impl.RepositoryAdminImpl.addRepository([RepositoryAdminImpl.java:94](http://repositoryadminimpl.java:94/))
	at dev.galasa.boot.felix.FelixFramework.loadBundleRepositories([FelixFramework.java:885](http://felixframework.java:885/))
	... 4 more
2024/05/09 12:03:06 JVM output: 09/05/2024 12:03:06.766 DEBUG dev.galasa.boot.felix.FelixFramework.stopFramework - Stopping Felix framework
2024/05/09 12:03:06 Don't have enough information to find the structure.json in the RAS folder.
2024/05/09 12:03:06 JVM output: 09/05/2024 12:03:06.791 DEBUG dev.galasa.boot.felix.FelixFramework.stopFramework - Felix framework stopped
2024/05/09 12:03:06 JVM output: 09/05/2024 12:03:06.816 ERROR dev.galasa.boot.Launcher.main - Exiting launcher due to exception
2024/05/09 12:03:06 JVM output: dev.galasa.boot.LauncherException: Unable to create and initialize Felix framework
	at dev.galasa.boot.Launcher.buildFramework([Launcher.java:221](http://launcher.java:221/))
	at dev.galasa.boot.Launcher.launch([Launcher.java:160](http://launcher.java:160/))
	at dev.galasa.boot.Launcher.main([Launcher.java:126](http://launcher.java:126/))
Caused by: dev.galasa.boot.LauncherException: Unable to load repository mvn:dev.galasa/dev.galasa.uber.obr/0.34.0/obr
	at dev.galasa.boot.felix.FelixFramework.loadBundleRepositories([FelixFramework.java:887](http://felixframework.java:887/))
2024/05/09 12:03:06 JVM output: at dev.galasa.boot.felix.FelixFramework.buildFramework([FelixFramework.java:120](http://felixframework.java:120/))
	at dev.galasa.boot.Launcher.buildFramework([Launcher.java:218](http://launcher.java:218/))
	... 2 more
Caused by: java.io.IOException: Unable to locate maven artifact mvn:dev.galasa/dev.galasa.uber.obr/0.34.0/obr
2024/05/09 12:03:06 JVM output: at dev.galasa.framework.maven.repository.internal.GalasaMavenUrlHandlerService.openConnection([GalasaMavenUrlHandlerService.java:78](http://galasamavenurlhandlerservice.java:78/))
2024/05/09 12:03:06 JVM output: at org.apache.felix.framework.URLHandlersStreamHandlerProxy.openConnection([URLHandlersStreamHandlerProxy.java:270](http://urlhandlersstreamhandlerproxy.java:270/))
	at java.base/java.net.URL.openConnection([URL.java:1074](http://url.java:1074/))
2024/05/09 12:03:06 JVM output: at org.apache.felix.bundlerepository.impl.FileUtil.openURL([FileUtil.java:199](http://fileutil.java:199/))
2024/05/09 12:03:06 JVM output: 
2024/05/09 12:03:06 JVM output: at org.apache.felix.bundlerepository.impl.DataModelHelperImpl.repository([DataModelHelperImpl.java:113](http://datamodelhelperimpl.java:113/))
2024/05/09 12:03:06 JVM output: 
2024/05/09 12:03:06 JVM output: at [org.apache.felix.bundlerepository.impl.RepositoryAdminImpl$1.run](http://org.apache.felix.bundlerepository.impl.repositoryadminimpl$1.run/)([RepositoryAdminImpl.java:115](http://repositoryadminimpl.java:115/))
2024/05/09 12:03:06 JVM output: 
2024/05/09 12:03:06 JVM output: at java.base/java.security.AccessController.doPrivileged(Native Method)
2024/05/09 12:03:06 JVM output: 
2024/05/09 12:03:06 JVM output: at org.apache.felix.bundlerepository.impl.RepositoryAdminImpl.addRepository([RepositoryAdminImpl.java:111](http://repositoryadminimpl.java:111/))
2024/05/09 12:03:06 JVM output: 
2024/05/09 12:03:06 JVM output: at org.apache.felix.bundlerepository.impl.RepositoryAdminImpl.addRepository([RepositoryAdminImpl.java:99](http://repositoryadminimpl.java:99/))
2024/05/09 12:03:06 JVM output: at org.apache.felix.bundlerepository.impl.RepositoryAdminImpl.addRepository([RepositoryAdminImpl.java:94](http://repositoryadminimpl.java:94/))
2024/05/09 12:03:06 JVM output: 
2024/05/09 12:03:06 JVM output: at dev.galasa.boot.felix.FelixFramework.loadBundleRepositories([FelixFramework.java:885](http://felixframework.java:885/))
2024/05/09 12:03:06 JVM output: ... 4 more
2024/05/09 12:03:06 JVM output: 
2024/05/09 12:03:06 Failed to wait for the JVM test to complete. exit status 16
2024/05/09 12:03:06 Don't have enough information to find the structure.json in the RAS folder.
2024/05/09 12:03:06 Interrupting the timing service sleeping. Test run  completed.
2024/05/09 12:03:07 Message received from JVM launch thread: DONE
2024/05/09 12:03:07 Don't have enough information to find the structure.json in the RAS folder.
2024/05/09 12:03:07 GAL1057E: The run identifier could not be detected in trace output of the child process
```

**Comment by galasa-team** [comment]
Build failed, see http://localhost:8001/api/v1/namespaces/tekton-pipelines/services/tekton-dashboard:http/proxy/#/namespaces/galasa-build/pipelineruns/repo-cli-pr-236-g6mf2 for details. If you are unable to do so, please contact a member of the Galasa team.

**Comment by techcobweb** [comment]
Ugh. Now the build is failing because of too many retries.

**Comment by galasa-team** [comment]
Build failed, see http://localhost:8001/api/v1/namespaces/tekton-pipelines/services/tekton-dashboard:http/proxy/#/namespaces/galasa-build/pipelineruns/repo-cli-pr-236-c6gl8 for details. If you are unable to do so, please contact a member of the Galasa team.

**Comment by galasa-team** [comment]
Build successful

**Comment by techcobweb** [comment]
Jade commented-out that test and is looking at it separately. Merging this change as a result.

**Pull request merged**
