### PR TITLE
Fiona holly 1330 portfolio flag

### PR DESCRIPTION
**Pull request by Wyvinar**
Started adding obr into the portfolio and using it in the JvmLauncher.

- Merged main into current branch
- Added documentation to the runs --bootstrap flag and edited build-locally.sh
- Added obr to portfolio and test selection
- Simplified code to make it clear only a single run is used over the launcher interface
- minor enhancements to test-galasactl-ecosystem
- portfolio obr is threaded through to the jvmlauncher validates that there is an obr
- deleter extra line in maven_test causing copyrighter to fail
- Squashed commits

- [ ] Console should have message logged to from JVM launcher when the test isn't able to run due to lack of OBR information
- [ ] runs submit local flags don't allow just a portfolio. They insist on class and obr currently.
- [ ] Unit test to pass a portfolio inside a mock file and check the tests get run.
- [ ] Remote launch should complain if stream information isn't there.

### CODE REVIEW

**Comment by galasa-team** [comment]
Build failed, see http://localhost:8001/api/v1/namespaces/tekton-pipelines/services/tekton-dashboard:http/proxy/#/namespaces/galasa-build/pipelineruns/repo-cli-pr-147-nd9cc for details. If you are unable to do so, please contact a member of the Galasa team.

**Comment by galasa-team** [comment]
Build failed, see http://localhost:8001/api/v1/namespaces/tekton-pipelines/services/tekton-dashboard:http/proxy/#/namespaces/galasa-build/pipelineruns/repo-cli-pr-147-55g8v for details. If you are unable to do so, please contact a member of the Galasa team.

**Comment by galasa-team** [comment]
Build failed, see http://localhost:8001/api/v1/namespaces/tekton-pipelines/services/tekton-dashboard:http/proxy/#/namespaces/galasa-build/pipelineruns/repo-cli-pr-147-psvcp for details. If you are unable to do so, please contact a member of the Galasa team.

**Comment by galasa-team** [comment]
Build failed, see http://localhost:8001/api/v1/namespaces/tekton-pipelines/services/tekton-dashboard:http/proxy/#/namespaces/galasa-build/pipelineruns/repo-cli-pr-147-xd4bg for details. If you are unable to do so, please contact a member of the Galasa team.

**Comment by techcobweb** [comment]
Abandoning this PR and branch in favour of launcher only ever launches one test at a time. No need to pass multiple classes #149

**Pull request closed without merging**
