### PR TITLE
Add --gradle and --maven flags to create Gradle and Maven test projects

### PR DESCRIPTION
**Pull request by eamansour**
(In progress)
For https://github.com/galasa-dev/projectmanagement/issues/1333

Main changes:
- Added `--maven` flag to allow Maven test projects to be created when running `galasactl project create` (this is the default option, so it does not need to be specified).
- Added `--gradle` flag to allow Gradle test projects to be created when running `galasactl project create`.
- Can specify both `--maven` and `--gradle` to create Maven and Gradle files in a test project.
- Added unit tests to cover both flags

### CODE REVIEW

**Comment by galasa-team** [comment]
Build successful

**Comment by galasa-team** [comment]
Build successful

**Comment by galasa-team** [comment]
Build successful

**Comment by galasa-team** [comment]
Build successful

**Comment by galasa-team** [comment]
Build successful

**Review by techcobweb — APPROVED** [review]

**Pull request merged**
