### PR TITLE
mcobbett versions from gradle file

### PR DESCRIPTION
**Pull request by techcobweb**
- read files through an interface from embedded
- build.gradle is the source of dependent versions of things

This PR is to stop the versions of things being hard-coded inside golang code.
The versions are hard to find, and aren't clear to anyone how to find and update them.

By putting the versions of things we depend upon into the build.gradle, we can use automation to extract them, put them into a build.properties file in the embedded folder, and include the file inside the built executable.

We can then use code at run-time to read that properties file, parse it, and supply the data versions to the surrounding Golang code.

This is a far less 'brittle' way of letting the golang code know what version it is running of things.

It replaces the mechanism used by `galasactl --version`, in that the `VERSION` file content is used now, because that value is added to the properties file which is read back.

### CODE REVIEW

**Comment by galasa-team** [comment]
Build successful

**Comment by galasa-team** [comment]
Build failed, see http://localhost:8001/api/v1/namespaces/tekton-pipelines/services/tekton-dashboard:http/proxy/#/namespaces/galasa-build/pipelineruns/repo-cli-pr-117-cckbv for details. If you are unable to do so, please contact a member of the Galasa team.

**Comment by galasa-team** [comment]
Build failed, see http://localhost:8001/api/v1/namespaces/tekton-pipelines/services/tekton-dashboard:http/proxy/#/namespaces/galasa-build/pipelineruns/repo-cli-pr-117-dspgn for details. If you are unable to do so, please contact a member of the Galasa team.

**Comment by galasa-team** [comment]
Build successful

**Review by hobbit1983 — APPROVED** [review]

**Comment by galasa-team** [comment]
Build failed, see http://localhost:8001/api/v1/namespaces/tekton-pipelines/services/tekton-dashboard:http/proxy/#/namespaces/galasa-build/pipelineruns/repo-cli-pr-117-fhkct for details. If you are unable to do so, please contact a member of the Galasa team.

**Pull request merged**
